baseURL = "/"
languageCode = "fr-fr"
title = "Pdelaby - Tutos"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn-pdy"
#theme = "ga-hugo-theme"

[params]
  description = "Pdelaby - Tutos"
  author = "Delaby Pierre"
  #showVisitedLinks = true
  themeVariant = "blue"


# For search functionnality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "/tags"
  weight = 30